// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appointmentAssignmentsReady = `-- name: AppointmentAssignmentsReady :one
SELECT (
    EXISTS (
        SELECT 1 FROM appointment_drivers ad JOIN drivers d ON d.id=ad.driver_id
        WHERE ad.appointment_id=$1::uuid AND ad.is_primary AND d.active
    )
    AND NOT EXISTS (
        SELECT 1 FROM appointment_drivers ad JOIN drivers d ON d.id=ad.driver_id
        WHERE ad.appointment_id=$1::uuid AND NOT d.active
    )
    AND EXISTS (
        SELECT 1 FROM appointment_resources ar JOIN resources r ON r.id=ar.resource_id
        WHERE ar.appointment_id=$1::uuid AND ar.purpose='chipping'
          AND r.resource_type='chipper' AND r.active
    )
    AND NOT EXISTS (
        SELECT 1 FROM appointment_resources ar JOIN resources r ON r.id=ar.resource_id
        WHERE ar.appointment_id=$1::uuid AND NOT r.active
    )
    AND (
        $2::text <> 'chipping_with_transport'
        OR ($3::text='external' AND $4::boolean)
        OR ($3::text='internal' AND EXISTS (
            SELECT 1 FROM appointment_resources ar JOIN resources r ON r.id=ar.resource_id
            WHERE ar.appointment_id=$1::uuid AND ar.purpose='transport'
              AND r.resource_type='transport_vehicle' AND r.active
        ))
    )
)::boolean
`

type AppointmentAssignmentsReadyParams struct {
	AppointmentID              pgtype.UUID
	JobType                    string
	TransportMode              string
	ExternalTransportConfirmed bool
}

func (q *Queries) AppointmentAssignmentsReady(ctx context.Context, arg AppointmentAssignmentsReadyParams) (bool, error) {
	row := q.db.QueryRow(ctx, appointmentAssignmentsReady,
		arg.AppointmentID,
		arg.JobType,
		arg.TransportMode,
		arg.ExternalTransportConfirmed,
	)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const bumpAppointmentVersion = `-- name: BumpAppointmentVersion :execrows
UPDATE appointments SET version = version + 1, updated_at = now()
WHERE id = $1::uuid AND version = $2
  AND lifecycle_status IN ('draft', 'proposal', 'fixed')
`

type BumpAppointmentVersionParams struct {
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) BumpAppointmentVersion(ctx context.Context, arg BumpAppointmentVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, bumpAppointmentVersion, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAppointmentAssignments = `-- name: DeleteAppointmentAssignments :exec
DELETE FROM appointment_drivers WHERE appointment_id = $1::uuid
`

func (q *Queries) DeleteAppointmentAssignments(ctx context.Context, appointmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointmentAssignments, appointmentID)
	return err
}

const deleteAppointmentResourceAssignments = `-- name: DeleteAppointmentResourceAssignments :exec
DELETE FROM appointment_resources WHERE appointment_id = $1::uuid
`

func (q *Queries) DeleteAppointmentResourceAssignments(ctx context.Context, appointmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointmentResourceAssignments, appointmentID)
	return err
}

const driverCanCompleteAppointment = `-- name: DriverCanCompleteAppointment :one
SELECT EXISTS (
    SELECT 1 FROM appointment_drivers ad
    JOIN drivers d ON d.id = ad.driver_id
    WHERE ad.appointment_id = $1::uuid
      AND ad.driver_id = $2::uuid
      AND d.active AND d.can_complete_jobs
)::boolean
`

type DriverCanCompleteAppointmentParams struct {
	AppointmentID pgtype.UUID
	DriverID      pgtype.UUID
}

func (q *Queries) DriverCanCompleteAppointment(ctx context.Context, arg DriverCanCompleteAppointmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, driverCanCompleteAppointment, arg.AppointmentID, arg.DriverID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const findAppointmentConflicts = `-- name: FindAppointmentConflicts :many
SELECT 'driver'::text AS conflict_type, d.driver_id::text AS subject_id, dr.display_name AS subject_name,
       a.id::text AS appointment_id, a.starts_at, a.ends_at, j.job_number,
       concat_ws(' ', NULLIF(c.first_name, ''), NULLIF(c.last_name, ''), NULLIF(c.company_name, ''))::text AS customer_name
FROM appointment_drivers d
JOIN drivers dr ON dr.id = d.driver_id
JOIN appointments a ON a.id = d.appointment_id
JOIN jobs j ON j.id=a.job_id
JOIN customers c ON c.id=j.customer_id
WHERE d.active AND d.driver_id = ANY($1::uuid[])
  AND d.reserved_range && tstzrange($2::timestamptz, $3::timestamptz, '[)')
  AND ($4::text = '' OR d.appointment_id <> $4::uuid)
UNION ALL
SELECT 'resource'::text, r.resource_id::text, rs.name,
       a.id::text, a.starts_at, a.ends_at, j.job_number,
       concat_ws(' ', NULLIF(c.first_name, ''), NULLIF(c.last_name, ''), NULLIF(c.company_name, ''))::text
FROM appointment_resources r
JOIN resources rs ON rs.id = r.resource_id
JOIN appointments a ON a.id = r.appointment_id
JOIN jobs j ON j.id=a.job_id
JOIN customers c ON c.id=j.customer_id
WHERE r.active AND r.exclusive AND r.resource_id = ANY($5::uuid[])
  AND r.reserved_range && tstzrange($2::timestamptz, $3::timestamptz, '[)')
  AND ($4::text = '' OR r.appointment_id <> $4::uuid)
ORDER BY starts_at, conflict_type, subject_name
`

type FindAppointmentConflictsParams struct {
	DriverIds            []pgtype.UUID
	FromUtc              pgtype.Timestamptz
	ToUtc                pgtype.Timestamptz
	ExcludeAppointmentID string
	ResourceIds          []pgtype.UUID
}

type FindAppointmentConflictsRow struct {
	ConflictType  string
	SubjectID     string
	SubjectName   string
	AppointmentID string
	StartsAt      pgtype.Timestamptz
	EndsAt        pgtype.Timestamptz
	JobNumber     string
	CustomerName  string
}

func (q *Queries) FindAppointmentConflicts(ctx context.Context, arg FindAppointmentConflictsParams) ([]FindAppointmentConflictsRow, error) {
	rows, err := q.db.Query(ctx, findAppointmentConflicts,
		arg.DriverIds,
		arg.FromUtc,
		arg.ToUtc,
		arg.ExcludeAppointmentID,
		arg.ResourceIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAppointmentConflictsRow{}
	for rows.Next() {
		var i FindAppointmentConflictsRow
		if err := rows.Scan(
			&i.ConflictType,
			&i.SubjectID,
			&i.SubjectName,
			&i.AppointmentID,
			&i.StartsAt,
			&i.EndsAt,
			&i.JobNumber,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAppointment = `-- name: GetAppointment :one
SELECT a.id::text, a.job_id::text, j.job_number, a.lifecycle_status, a.confirmation_status,
       a.starts_at, a.ends_at, a.buffer_before_minutes, a.buffer_after_minutes,
       COALESCE(a.availability_override_reason, '')::text AS availability_override_reason,
       a.version, j.workflow_status, j.job_type, j.transport_mode,
       j.external_transport_confirmed, j.estimated_hack_minutes, j.estimated_transport_minutes
FROM appointments a
JOIN jobs j ON j.id = a.job_id
WHERE a.id = $1::uuid
`

type GetAppointmentRow struct {
	AID                        string
	AJobID                     string
	JobNumber                  string
	LifecycleStatus            string
	ConfirmationStatus         string
	StartsAt                   pgtype.Timestamptz
	EndsAt                     pgtype.Timestamptz
	BufferBeforeMinutes        int32
	BufferAfterMinutes         int32
	AvailabilityOverrideReason string
	Version                    int32
	WorkflowStatus             string
	JobType                    string
	TransportMode              string
	ExternalTransportConfirmed bool
	EstimatedHackMinutes       int32
	EstimatedTransportMinutes  int32
}

func (q *Queries) GetAppointment(ctx context.Context, id pgtype.UUID) (GetAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getAppointment, id)
	var i GetAppointmentRow
	err := row.Scan(
		&i.AID,
		&i.AJobID,
		&i.JobNumber,
		&i.LifecycleStatus,
		&i.ConfirmationStatus,
		&i.StartsAt,
		&i.EndsAt,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.AvailabilityOverrideReason,
		&i.Version,
		&i.WorkflowStatus,
		&i.JobType,
		&i.TransportMode,
		&i.ExternalTransportConfirmed,
		&i.EstimatedHackMinutes,
		&i.EstimatedTransportMinutes,
	)
	return i, err
}

const getAppointmentDetail = `-- name: GetAppointmentDetail :one
SELECT a.id::text, a.job_id::text, j.job_number, a.lifecycle_status, a.confirmation_status,
       a.starts_at, a.ends_at, a.buffer_before_minutes, a.buffer_after_minutes, a.version,
       j.workflow_status, j.job_type, j.transport_mode, j.external_transport_confirmed,
       j.estimated_hack_minutes, j.estimated_transport_minutes, j.volume_m3::text, c.id::text AS customer_id,
       concat_ws(' ', NULLIF(c.first_name, ''), NULLIF(c.last_name, ''), NULLIF(c.company_name, ''))::text AS customer_name,
       c.locality, c.street, c.postal_code,
       COALESCE(j.pile_latitude::text, '')::text AS latitude,
       COALESCE(j.pile_longitude::text, '')::text AS longitude,
       COALESCE(c.phone_raw, '')::text AS phone,
       COALESCE(c.email::text, '')::text AS email,
       c.notification_preference
FROM appointments a
JOIN jobs j ON j.id = a.job_id
JOIN customers c ON c.id = j.customer_id
WHERE a.id = $1::uuid
`

type GetAppointmentDetailRow struct {
	AID                        string
	AJobID                     string
	JobNumber                  string
	LifecycleStatus            string
	ConfirmationStatus         string
	StartsAt                   pgtype.Timestamptz
	EndsAt                     pgtype.Timestamptz
	BufferBeforeMinutes        int32
	BufferAfterMinutes         int32
	Version                    int32
	WorkflowStatus             string
	JobType                    string
	TransportMode              string
	ExternalTransportConfirmed bool
	EstimatedHackMinutes       int32
	EstimatedTransportMinutes  int32
	JVolumeM3                  string
	CustomerID                 string
	CustomerName               string
	Locality                   string
	Street                     string
	PostalCode                 string
	Latitude                   string
	Longitude                  string
	Phone                      string
	Email                      string
	NotificationPreference     string
}

func (q *Queries) GetAppointmentDetail(ctx context.Context, id pgtype.UUID) (GetAppointmentDetailRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentDetail, id)
	var i GetAppointmentDetailRow
	err := row.Scan(
		&i.AID,
		&i.AJobID,
		&i.JobNumber,
		&i.LifecycleStatus,
		&i.ConfirmationStatus,
		&i.StartsAt,
		&i.EndsAt,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.Version,
		&i.WorkflowStatus,
		&i.JobType,
		&i.TransportMode,
		&i.ExternalTransportConfirmed,
		&i.EstimatedHackMinutes,
		&i.EstimatedTransportMinutes,
		&i.JVolumeM3,
		&i.CustomerID,
		&i.CustomerName,
		&i.Locality,
		&i.Street,
		&i.PostalCode,
		&i.Latitude,
		&i.Longitude,
		&i.Phone,
		&i.Email,
		&i.NotificationPreference,
	)
	return i, err
}

const getAppointmentForUpdate = `-- name: GetAppointmentForUpdate :one
SELECT a.id::text, a.job_id::text, a.lifecycle_status, a.confirmation_status,
       a.starts_at, a.ends_at, a.buffer_before_minutes, a.buffer_after_minutes,
       COALESCE(a.availability_override_reason, '')::text AS availability_override_reason,
       COALESCE(a.cancellation_reason, '')::text AS cancellation_reason,
       a.version, j.workflow_status, j.job_type, j.transport_mode,
       j.external_transport_confirmed, j.estimated_hack_minutes, j.estimated_transport_minutes
FROM appointments a
JOIN jobs j ON j.id = a.job_id
WHERE a.id = $1::uuid
FOR UPDATE OF a, j
`

type GetAppointmentForUpdateRow struct {
	AID                        string
	AJobID                     string
	LifecycleStatus            string
	ConfirmationStatus         string
	StartsAt                   pgtype.Timestamptz
	EndsAt                     pgtype.Timestamptz
	BufferBeforeMinutes        int32
	BufferAfterMinutes         int32
	AvailabilityOverrideReason string
	CancellationReason         string
	Version                    int32
	WorkflowStatus             string
	JobType                    string
	TransportMode              string
	ExternalTransportConfirmed bool
	EstimatedHackMinutes       int32
	EstimatedTransportMinutes  int32
}

func (q *Queries) GetAppointmentForUpdate(ctx context.Context, id pgtype.UUID) (GetAppointmentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentForUpdate, id)
	var i GetAppointmentForUpdateRow
	err := row.Scan(
		&i.AID,
		&i.AJobID,
		&i.LifecycleStatus,
		&i.ConfirmationStatus,
		&i.StartsAt,
		&i.EndsAt,
		&i.BufferBeforeMinutes,
		&i.BufferAfterMinutes,
		&i.AvailabilityOverrideReason,
		&i.CancellationReason,
		&i.Version,
		&i.WorkflowStatus,
		&i.JobType,
		&i.TransportMode,
		&i.ExternalTransportConfirmed,
		&i.EstimatedHackMinutes,
		&i.EstimatedTransportMinutes,
	)
	return i, err
}

const getPlanningJob = `-- name: GetPlanningJob :one
SELECT j.id::text, j.job_number, j.workflow_status, j.job_type, j.transport_mode,
       j.external_transport_confirmed, j.estimated_hack_minutes, j.archived_at,
       COALESCE(w.id::text, '')::text AS waitlist_id, COALESCE(w.version, 0)::integer AS waitlist_version
FROM jobs j
LEFT JOIN waitlist_entries w ON w.job_id = j.id AND w.removed_at IS NULL
WHERE j.id = $1::uuid
FOR UPDATE OF j
`

type GetPlanningJobRow struct {
	JID                        string
	JobNumber                  string
	WorkflowStatus             string
	JobType                    string
	TransportMode              string
	ExternalTransportConfirmed bool
	EstimatedHackMinutes       int32
	ArchivedAt                 pgtype.Timestamptz
	WaitlistID                 string
	WaitlistVersion            int32
}

func (q *Queries) GetPlanningJob(ctx context.Context, id pgtype.UUID) (GetPlanningJobRow, error) {
	row := q.db.QueryRow(ctx, getPlanningJob, id)
	var i GetPlanningJobRow
	err := row.Scan(
		&i.JID,
		&i.JobNumber,
		&i.WorkflowStatus,
		&i.JobType,
		&i.TransportMode,
		&i.ExternalTransportConfirmed,
		&i.EstimatedHackMinutes,
		&i.ArchivedAt,
		&i.WaitlistID,
		&i.WaitlistVersion,
	)
	return i, err
}

const insertAppointmentDraft = `-- name: InsertAppointmentDraft :one
INSERT INTO appointments (job_id, starts_at, ends_at, buffer_before_minutes, buffer_after_minutes)
VALUES ($1::uuid, $2::timestamptz, $3::timestamptz,
        $4, $5)
RETURNING id::text, version
`

type InsertAppointmentDraftParams struct {
	JobID               pgtype.UUID
	StartsAt            pgtype.Timestamptz
	EndsAt              pgtype.Timestamptz
	BufferBeforeMinutes int32
	BufferAfterMinutes  int32
}

type InsertAppointmentDraftRow struct {
	ID      string
	Version int32
}

func (q *Queries) InsertAppointmentDraft(ctx context.Context, arg InsertAppointmentDraftParams) (InsertAppointmentDraftRow, error) {
	row := q.db.QueryRow(ctx, insertAppointmentDraft,
		arg.JobID,
		arg.StartsAt,
		arg.EndsAt,
		arg.BufferBeforeMinutes,
		arg.BufferAfterMinutes,
	)
	var i InsertAppointmentDraftRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const insertAppointmentDriver = `-- name: InsertAppointmentDriver :execrows
INSERT INTO appointment_drivers (
    appointment_id, driver_id, is_primary, active, reserved_starts_at, reserved_ends_at
)
SELECT a.id, $1::uuid, $2,
       a.lifecycle_status IN ('proposal', 'fixed'),
       a.starts_at - make_interval(mins => a.buffer_before_minutes),
       a.ends_at + make_interval(mins => a.buffer_after_minutes)
FROM appointments a
JOIN drivers d ON d.id = $1::uuid AND d.active
WHERE a.id = $3::uuid
`

type InsertAppointmentDriverParams struct {
	DriverID      pgtype.UUID
	IsPrimary     bool
	AppointmentID pgtype.UUID
}

func (q *Queries) InsertAppointmentDriver(ctx context.Context, arg InsertAppointmentDriverParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAppointmentDriver, arg.DriverID, arg.IsPrimary, arg.AppointmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAppointmentResource = `-- name: InsertAppointmentResource :execrows
INSERT INTO appointment_resources (
    appointment_id, resource_id, purpose, exclusive, active, reserved_starts_at, reserved_ends_at
)
SELECT a.id, r.id, $1, r.exclusive,
       a.lifecycle_status IN ('proposal', 'fixed'),
       a.starts_at - make_interval(mins => a.buffer_before_minutes),
       a.ends_at + make_interval(mins => a.buffer_after_minutes)
FROM appointments a
JOIN resources r ON r.id = $2::uuid AND r.active
WHERE a.id = $3::uuid
`

type InsertAppointmentResourceParams struct {
	Purpose       string
	ResourceID    pgtype.UUID
	AppointmentID pgtype.UUID
}

func (q *Queries) InsertAppointmentResource(ctx context.Context, arg InsertAppointmentResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAppointmentResource, arg.Purpose, arg.ResourceID, arg.AppointmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (event_type, aggregate_type, aggregate_id, payload, idempotency_key, status, processed_at)
VALUES ($1, 'appointment', $2::uuid,
        $3::jsonb, $4, 'processed', now())
ON CONFLICT (idempotency_key) DO NOTHING
`

type InsertOutboxEventParams struct {
	EventType      string
	AggregateID    pgtype.UUID
	Payload        []byte
	IdempotencyKey string
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.EventType,
		arg.AggregateID,
		arg.Payload,
		arg.IdempotencyKey,
	)
	return err
}

const listActiveDriversForPlanning = `-- name: ListActiveDriversForPlanning :many
SELECT id::text, display_name, can_complete_jobs FROM drivers WHERE active ORDER BY lower(display_name), id
`

type ListActiveDriversForPlanningRow struct {
	ID              string
	DisplayName     string
	CanCompleteJobs bool
}

func (q *Queries) ListActiveDriversForPlanning(ctx context.Context) ([]ListActiveDriversForPlanningRow, error) {
	rows, err := q.db.Query(ctx, listActiveDriversForPlanning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDriversForPlanningRow{}
	for rows.Next() {
		var i ListActiveDriversForPlanningRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.CanCompleteJobs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveResourcesForPlanning = `-- name: ListActiveResourcesForPlanning :many
SELECT id::text, name, resource_type, exclusive FROM resources WHERE active ORDER BY resource_type, lower(name), id
`

type ListActiveResourcesForPlanningRow struct {
	ID           string
	Name         string
	ResourceType string
	Exclusive    bool
}

func (q *Queries) ListActiveResourcesForPlanning(ctx context.Context) ([]ListActiveResourcesForPlanningRow, error) {
	rows, err := q.db.Query(ctx, listActiveResourcesForPlanning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveResourcesForPlanningRow{}
	for rows.Next() {
		var i ListActiveResourcesForPlanningRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ResourceType,
			&i.Exclusive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentDrivers = `-- name: ListAppointmentDrivers :many
SELECT ad.appointment_id::text AS appointment_id, ad.driver_id::text AS driver_id, d.display_name, ad.is_primary
FROM appointment_drivers ad JOIN drivers d ON d.id = ad.driver_id
WHERE ad.appointment_id = ANY($1::uuid[])
ORDER BY ad.appointment_id, ad.is_primary DESC, lower(d.display_name)
`

type ListAppointmentDriversRow struct {
	AppointmentID string
	DriverID      string
	DisplayName   string
	IsPrimary     bool
}

func (q *Queries) ListAppointmentDrivers(ctx context.Context, appointmentIds []pgtype.UUID) ([]ListAppointmentDriversRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentDrivers, appointmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentDriversRow{}
	for rows.Next() {
		var i ListAppointmentDriversRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.DriverID,
			&i.DisplayName,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentResources = `-- name: ListAppointmentResources :many
SELECT ar.appointment_id::text AS appointment_id, ar.resource_id::text AS resource_id, r.name, r.resource_type, ar.purpose
FROM appointment_resources ar JOIN resources r ON r.id = ar.resource_id
WHERE ar.appointment_id = ANY($1::uuid[])
ORDER BY ar.appointment_id, lower(r.name)
`

type ListAppointmentResourcesRow struct {
	AppointmentID string
	ResourceID    string
	Name          string
	ResourceType  string
	Purpose       string
}

func (q *Queries) ListAppointmentResources(ctx context.Context, appointmentIds []pgtype.UUID) ([]ListAppointmentResourcesRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentResources, appointmentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentResourcesRow{}
	for rows.Next() {
		var i ListAppointmentResourcesRow
		if err := rows.Scan(
			&i.AppointmentID,
			&i.ResourceID,
			&i.Name,
			&i.ResourceType,
			&i.Purpose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarAppointments = `-- name: ListCalendarAppointments :many
SELECT a.id::text, a.job_id::text, j.job_number, a.lifecycle_status, a.confirmation_status,
       a.starts_at, a.ends_at, a.buffer_before_minutes, a.buffer_after_minutes, a.version,
       j.job_type, j.volume_m3::text, c.id::text AS customer_id,
       concat_ws(' ', NULLIF(c.first_name, ''), NULLIF(c.last_name, ''), NULLIF(c.company_name, ''))::text AS customer_name,
       c.locality, c.street, c.postal_code,
       COALESCE(j.pile_latitude::text, '')::text AS latitude,
       COALESCE(j.pile_longitude::text, '')::text AS longitude
FROM appointments a
JOIN jobs j ON j.id = a.job_id
JOIN customers c ON c.id = j.customer_id
WHERE a.starts_at < $1::timestamptz AND a.ends_at > $2::timestamptz
ORDER BY a.starts_at, a.id
`

type ListCalendarAppointmentsParams struct {
	ToUtc   pgtype.Timestamptz
	FromUtc pgtype.Timestamptz
}

type ListCalendarAppointmentsRow struct {
	AID                 string
	AJobID              string
	JobNumber           string
	LifecycleStatus     string
	ConfirmationStatus  string
	StartsAt            pgtype.Timestamptz
	EndsAt              pgtype.Timestamptz
	BufferBeforeMinutes int32
	BufferAfterMinutes  int32
	Version             int32
	JobType             string
	JVolumeM3           string
	CustomerID          string
	CustomerName        string
	Locality            string
	Street              string
	PostalCode          string
	Latitude            string
	Longitude           string
}

func (q *Queries) ListCalendarAppointments(ctx context.Context, arg ListCalendarAppointmentsParams) ([]ListCalendarAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listCalendarAppointments, arg.ToUtc, arg.FromUtc)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarAppointmentsRow{}
	for rows.Next() {
		var i ListCalendarAppointmentsRow
		if err := rows.Scan(
			&i.AID,
			&i.AJobID,
			&i.JobNumber,
			&i.LifecycleStatus,
			&i.ConfirmationStatus,
			&i.StartsAt,
			&i.EndsAt,
			&i.BufferBeforeMinutes,
			&i.BufferAfterMinutes,
			&i.Version,
			&i.JobType,
			&i.JVolumeM3,
			&i.CustomerID,
			&i.CustomerName,
			&i.Locality,
			&i.Street,
			&i.PostalCode,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaitlistForPlanning = `-- name: ListWaitlistForPlanning :many
SELECT w.id::text AS waitlist_id, j.id::text AS job_id, j.job_number,
       j.job_type, j.volume_m3::text, j.estimated_hack_minutes,
       concat_ws(' ', NULLIF(c.first_name, ''), NULLIF(c.last_name, ''), NULLIF(c.company_name, ''))::text AS customer_name,
       c.locality
FROM waitlist_entries w
JOIN jobs j ON j.id = w.job_id
JOIN customers c ON c.id = j.customer_id
WHERE w.removed_at IS NULL AND j.archived_at IS NULL AND j.workflow_status = 'waitlist'
ORDER BY w.manual_priority DESC, w.entered_at, w.id
`

type ListWaitlistForPlanningRow struct {
	WaitlistID           string
	JobID                string
	JobNumber            string
	JobType              string
	JVolumeM3            string
	EstimatedHackMinutes int32
	CustomerName         string
	Locality             string
}

func (q *Queries) ListWaitlistForPlanning(ctx context.Context) ([]ListWaitlistForPlanningRow, error) {
	rows, err := q.db.Query(ctx, listWaitlistForPlanning)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWaitlistForPlanningRow{}
	for rows.Next() {
		var i ListWaitlistForPlanningRow
		if err := rows.Scan(
			&i.WaitlistID,
			&i.JobID,
			&i.JobNumber,
			&i.JobType,
			&i.JVolumeM3,
			&i.EstimatedHackMinutes,
			&i.CustomerName,
			&i.Locality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppointmentDrivers = `-- name: LockAppointmentDrivers :many
SELECT d.id::text
FROM appointment_drivers ad
JOIN drivers d ON d.id = ad.driver_id
WHERE ad.appointment_id = $1::uuid
ORDER BY d.id
FOR SHARE OF d
`

func (q *Queries) LockAppointmentDrivers(ctx context.Context, appointmentID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, lockAppointmentDrivers, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var d_id string
		if err := rows.Scan(&d_id); err != nil {
			return nil, err
		}
		items = append(items, d_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAppointmentResources = `-- name: LockAppointmentResources :many
SELECT r.id::text
FROM appointment_resources ar
JOIN resources r ON r.id = ar.resource_id
WHERE ar.appointment_id = $1::uuid
ORDER BY r.id
FOR SHARE OF r
`

func (q *Queries) LockAppointmentResources(ctx context.Context, appointmentID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, lockAppointmentResources, appointmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var r_id string
		if err := rows.Scan(&r_id); err != nil {
			return nil, err
		}
		items = append(items, r_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSchedulingMutation = `-- name: LockSchedulingMutation :exec
SELECT pg_advisory_xact_lock(1214342235, 1396919884)
`

// Serialize changes that can invalidate routing/travel-time suggestions. Row
// locks alone cannot protect against newly inserted or non-overlapping moves.
func (q *Queries) LockSchedulingMutation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockSchedulingMutation)
	return err
}

const prepareAppointmentSwap = `-- name: PrepareAppointmentSwap :execrows
UPDATE appointments
SET lifecycle_status='draft', updated_at=now()
WHERE id=$1::uuid AND version=$2
  AND lifecycle_status IN ('draft', 'proposal')
`

type PrepareAppointmentSwapParams struct {
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) PrepareAppointmentSwap(ctx context.Context, arg PrepareAppointmentSwapParams) (int64, error) {
	result, err := q.db.Exec(ctx, prepareAppointmentSwap, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const refreshAppointmentReservations = `-- name: RefreshAppointmentReservations :exec
UPDATE appointment_drivers d SET
    active = a.lifecycle_status IN ('proposal', 'fixed'),
    reserved_starts_at = a.starts_at - make_interval(mins => a.buffer_before_minutes),
    reserved_ends_at = a.ends_at + make_interval(mins => a.buffer_after_minutes)
FROM appointments a WHERE a.id = d.appointment_id AND a.id = $1::uuid
`

func (q *Queries) RefreshAppointmentReservations(ctx context.Context, appointmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshAppointmentReservations, appointmentID)
	return err
}

const refreshAppointmentResourceReservations = `-- name: RefreshAppointmentResourceReservations :exec
UPDATE appointment_resources r SET
    active = a.lifecycle_status IN ('proposal', 'fixed'),
    exclusive = source.exclusive,
    reserved_starts_at = a.starts_at - make_interval(mins => a.buffer_before_minutes),
    reserved_ends_at = a.ends_at + make_interval(mins => a.buffer_after_minutes)
FROM appointments a, resources source
WHERE a.id = r.appointment_id AND source.id=r.resource_id AND a.id = $1::uuid
`

func (q *Queries) RefreshAppointmentResourceReservations(ctx context.Context, appointmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshAppointmentResourceReservations, appointmentID)
	return err
}

const removeWaitlistScheduled = `-- name: RemoveWaitlistScheduled :exec
UPDATE waitlist_entries SET removed_at = now(), removed_reason = 'scheduled', version = version + 1
WHERE job_id = $1::uuid AND removed_at IS NULL
`

func (q *Queries) RemoveWaitlistScheduled(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeWaitlistScheduled, jobID)
	return err
}

const reopenCancelledAppointment = `-- name: ReopenCancelledAppointment :execrows
UPDATE appointments SET lifecycle_status = 'proposal',
    confirmation_status = 'not_requested',
    availability_override_reason = NULLIF($1::text, ''),
    notification_override_reason = NULL,
    fixed_by_user_id = NULL, fixed_at = NULL,
    cancelled_by_user_id = NULL, cancelled_at = NULL, cancellation_reason = NULL,
    version = version + 1, updated_at = now()
WHERE id = $2::uuid AND version = $3
  AND lifecycle_status = 'cancelled'
`

type ReopenCancelledAppointmentParams struct {
	AvailabilityOverrideReason string
	ID                         pgtype.UUID
	ExpectedVersion            int32
}

func (q *Queries) ReopenCancelledAppointment(ctx context.Context, arg ReopenCancelledAppointmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, reopenCancelledAppointment, arg.AvailabilityOverrideReason, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreAppointmentSwapStatus = `-- name: RestoreAppointmentSwapStatus :execrows
UPDATE appointments
SET lifecycle_status=$1, updated_at=now()
WHERE id=$2::uuid AND version=$3
  AND lifecycle_status='draft'
`

type RestoreAppointmentSwapStatusParams struct {
	LifecycleStatus string
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) RestoreAppointmentSwapStatus(ctx context.Context, arg RestoreAppointmentSwapStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreAppointmentSwapStatus, arg.LifecycleStatus, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreWaitlistAfterCancellation = `-- name: RestoreWaitlistAfterCancellation :exec
INSERT INTO waitlist_entries (job_id)
SELECT $1::uuid
WHERE NOT EXISTS (SELECT 1 FROM waitlist_entries WHERE job_id = $1::uuid AND removed_at IS NULL)
`

func (q *Queries) RestoreWaitlistAfterCancellation(ctx context.Context, jobID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreWaitlistAfterCancellation, jobID)
	return err
}

const setAppointmentCancelled = `-- name: SetAppointmentCancelled :execrows
UPDATE appointments SET lifecycle_status = 'cancelled',
    cancelled_by_user_id = $1::uuid, cancelled_at = now(),
    cancellation_reason = NULLIF($2::text, ''),
    version = version + 1, updated_at = now()
WHERE id = $3::uuid AND version = $4
  AND lifecycle_status IN ('draft', 'proposal', 'fixed')
`

type SetAppointmentCancelledParams struct {
	ActorUserID     pgtype.UUID
	Reason          string
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetAppointmentCancelled(ctx context.Context, arg SetAppointmentCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppointmentCancelled,
		arg.ActorUserID,
		arg.Reason,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppointmentCompleted = `-- name: SetAppointmentCompleted :execrows
UPDATE appointments SET lifecycle_status = 'completed',
    completed_by_user_id = $1::uuid, completed_at = now(),
    completion_override_reason = NULLIF($2::text, ''),
    version = version + 1, updated_at = now()
WHERE id = $3::uuid AND version = $4 AND lifecycle_status = 'fixed'
`

type SetAppointmentCompletedParams struct {
	ActorUserID     pgtype.UUID
	OverrideReason  string
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetAppointmentCompleted(ctx context.Context, arg SetAppointmentCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppointmentCompleted,
		arg.ActorUserID,
		arg.OverrideReason,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppointmentFixed = `-- name: SetAppointmentFixed :execrows
UPDATE appointments SET lifecycle_status = 'fixed', confirmation_status = 'pending',
    fixed_by_user_id = $1::uuid, fixed_at = now(),
    version = version + 1, updated_at = now()
WHERE id = $2::uuid AND version = $3 AND lifecycle_status = 'proposal'
`

type SetAppointmentFixedParams struct {
	ActorUserID     pgtype.UUID
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetAppointmentFixed(ctx context.Context, arg SetAppointmentFixedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppointmentFixed, arg.ActorUserID, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAppointmentOverrideReason = `-- name: SetAppointmentOverrideReason :exec
UPDATE appointments SET availability_override_reason = NULLIF($1::text, '')
WHERE id = $2::uuid
`

type SetAppointmentOverrideReasonParams struct {
	Reason string
	ID     pgtype.UUID
}

func (q *Queries) SetAppointmentOverrideReason(ctx context.Context, arg SetAppointmentOverrideReasonParams) error {
	_, err := q.db.Exec(ctx, setAppointmentOverrideReason, arg.Reason, arg.ID)
	return err
}

const setAppointmentProposal = `-- name: SetAppointmentProposal :execrows
UPDATE appointments SET lifecycle_status = 'proposal', version = version + 1, updated_at = now()
WHERE id = $1::uuid AND version = $2 AND lifecycle_status = 'draft'
`

type SetAppointmentProposalParams struct {
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) SetAppointmentProposal(ctx context.Context, arg SetAppointmentProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAppointmentProposal, arg.ID, arg.ExpectedVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setJobWorkflow = `-- name: SetJobWorkflow :exec
UPDATE jobs SET workflow_status = $1, version = version + 1, updated_at = now()
WHERE id = $2::uuid
`

type SetJobWorkflowParams struct {
	WorkflowStatus string
	JobID          pgtype.UUID
}

func (q *Queries) SetJobWorkflow(ctx context.Context, arg SetJobWorkflowParams) error {
	_, err := q.db.Exec(ctx, setJobWorkflow, arg.WorkflowStatus, arg.JobID)
	return err
}

const updateAppointmentTime = `-- name: UpdateAppointmentTime :execrows
UPDATE appointments SET starts_at = $1::timestamptz,
    ends_at = $2::timestamptz,
    confirmation_status = CASE WHEN lifecycle_status = 'fixed' THEN 'pending' ELSE confirmation_status END,
    version = version + 1, updated_at = now()
WHERE id = $3::uuid AND version = $4
  AND lifecycle_status IN ('draft', 'proposal', 'fixed')
`

type UpdateAppointmentTimeParams struct {
	StartsAt        pgtype.Timestamptz
	EndsAt          pgtype.Timestamptz
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateAppointmentTime(ctx context.Context, arg UpdateAppointmentTimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppointmentTime,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
