// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardCounts = `-- name: GetDashboardCounts :one
SELECT
    (SELECT count(*) FROM waitlist_entries w JOIN jobs j ON j.id=w.job_id JOIN customers c ON c.id=j.customer_id
     WHERE w.removed_at IS NULL AND j.archived_at IS NULL AND c.archived_at IS NULL)::bigint AS waitlist_count,
    (SELECT count(*) FROM appointments a
     WHERE a.starts_at < $1::timestamptz AND a.ends_at > $2::timestamptz
       AND a.lifecycle_status IN ('proposal','fixed'))::bigint AS appointment_count,
    (SELECT count(*) FROM appointments a
     WHERE a.starts_at < $3::timestamptz AND a.ends_at > $2::timestamptz
       AND a.lifecycle_status='fixed' AND a.confirmation_status IN ('pending','declined','callback_requested'))::bigint AS attention_count,
    (SELECT count(*) FROM appointments a
       JOIN confirmation_requests cr ON cr.appointment_id=a.id AND cr.status='active'
     WHERE a.starts_at < $3::timestamptz AND a.ends_at > $2::timestamptz
       AND a.lifecycle_status='fixed' AND a.confirmation_status='pending'
       AND cr.created_at <= $4::timestamptz)::bigint AS overdue_confirmation_count,
    (SELECT count(*) FROM appointments a
     WHERE a.starts_at < $3::timestamptz AND a.ends_at > $2::timestamptz
       AND a.lifecycle_status='fixed' AND a.confirmation_status='declined')::bigint AS declined_confirmation_count,
    (SELECT count(*) FROM appointments a
     WHERE a.starts_at < $3::timestamptz AND a.ends_at > $2::timestamptz
       AND a.lifecycle_status='fixed' AND a.confirmation_status='callback_requested')::bigint AS callback_request_count,
    (SELECT count(*) FROM waitlist_entries w JOIN jobs j ON j.id=w.job_id JOIN customers c ON c.id=j.customer_id
     WHERE w.removed_at IS NULL AND j.archived_at IS NULL AND c.archived_at IS NULL
       AND NOT EXISTS (SELECT 1 FROM appointments a WHERE a.job_id=j.id AND a.lifecycle_status IN ('proposal','fixed')))::bigint AS unplanned_count,
    (SELECT count(*) FROM notifications n
       JOIN confirmation_requests cr ON cr.id=n.confirmation_request_id AND cr.status='active'
       JOIN appointments a ON a.id=n.appointment_id AND a.lifecycle_status='fixed'
     WHERE n.status IN ('retry_wait','failed')
        OR (n.status IN ('queued','sending') AND n.updated_at <= $4::timestamptz))::bigint AS notification_issue_count,
    (SELECT count(*) FROM appointments a
     WHERE a.starts_at < $3::timestamptz AND a.ends_at > $2::timestamptz
       AND a.lifecycle_status IN ('proposal','fixed') AND a.availability_override_reason IS NOT NULL)::bigint AS override_count,
    (SELECT count(*) FROM drivers d WHERE d.active)::bigint AS active_driver_count,
    (SELECT count(*) FROM voice_drafts v
     WHERE v.owner_user_id=$5::uuid AND v.status='needs_review' AND v.expires_at>now())::bigint AS voice_draft_count
`

type GetDashboardCountsParams struct {
	DayEnd        pgtype.Timestamptz
	DayStart      pgtype.Timestamptz
	HorizonEnd    pgtype.Timestamptz
	PendingBefore pgtype.Timestamptz
	OwnerUserID   pgtype.UUID
}

type GetDashboardCountsRow struct {
	WaitlistCount             int64
	AppointmentCount          int64
	AttentionCount            int64
	OverdueConfirmationCount  int64
	DeclinedConfirmationCount int64
	CallbackRequestCount      int64
	UnplannedCount            int64
	NotificationIssueCount    int64
	OverrideCount             int64
	ActiveDriverCount         int64
	VoiceDraftCount           int64
}

func (q *Queries) GetDashboardCounts(ctx context.Context, arg GetDashboardCountsParams) (GetDashboardCountsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardCounts,
		arg.DayEnd,
		arg.DayStart,
		arg.HorizonEnd,
		arg.PendingBefore,
		arg.OwnerUserID,
	)
	var i GetDashboardCountsRow
	err := row.Scan(
		&i.WaitlistCount,
		&i.AppointmentCount,
		&i.AttentionCount,
		&i.OverdueConfirmationCount,
		&i.DeclinedConfirmationCount,
		&i.CallbackRequestCount,
		&i.UnplannedCount,
		&i.NotificationIssueCount,
		&i.OverrideCount,
		&i.ActiveDriverCount,
		&i.VoiceDraftCount,
	)
	return i, err
}

const listDashboardAppointments = `-- name: ListDashboardAppointments :many
SELECT a.id::text, a.job_id::text, j.customer_id::text AS customer_id, j.job_number, a.lifecycle_status, a.confirmation_status,
       a.starts_at, a.ends_at, a.version, j.job_type, j.volume_m3::text,
       concat_ws(' ', NULLIF(c.first_name,''), NULLIF(c.last_name,''), NULLIF(c.company_name,''))::text AS customer_name,
       c.street, c.postal_code, c.locality, c.country_code,
       COALESCE(j.pile_latitude::text, '')::text AS latitude, COALESCE(j.pile_longitude::text, '')::text AS longitude,
       COALESCE(string_agg(DISTINCT d.display_name, ', ' ORDER BY d.display_name) FILTER (WHERE d.id IS NOT NULL), '')::text AS driver_names,
       COALESCE(string_agg(DISTINCT r.name, ', ' ORDER BY r.name) FILTER (WHERE r.id IS NOT NULL), '')::text AS resource_names,
       COALESCE(string_agg(DISTINCT r.name, ', ' ORDER BY r.name) FILTER (WHERE r.resource_type='chipper'), '')::text AS chipper_names,
       COALESCE((SELECT n.body FROM job_notes n WHERE n.job_id=j.id ORDER BY n.created_at DESC, n.id DESC LIMIT 1), '')::text AS latest_note,
       COALESCE(a.availability_override_reason, '')::text AS availability_override_reason
FROM appointments a
JOIN jobs j ON j.id=a.job_id
JOIN customers c ON c.id=j.customer_id
LEFT JOIN appointment_drivers ad ON ad.appointment_id=a.id
LEFT JOIN drivers d ON d.id=ad.driver_id
LEFT JOIN appointment_resources ar ON ar.appointment_id=a.id
LEFT JOIN resources r ON r.id=ar.resource_id
WHERE a.starts_at < $1::timestamptz AND a.ends_at > $2::timestamptz
  AND a.lifecycle_status IN ('proposal','fixed')
GROUP BY a.id, j.id, c.id
ORDER BY a.starts_at, a.id
LIMIT $3
`

type ListDashboardAppointmentsParams struct {
	RangeEnd    pgtype.Timestamptz
	RangeStart  pgtype.Timestamptz
	ResultLimit int32
}

type ListDashboardAppointmentsRow struct {
	AID                        string
	AJobID                     string
	CustomerID                 string
	JobNumber                  string
	LifecycleStatus            string
	ConfirmationStatus         string
	StartsAt                   pgtype.Timestamptz
	EndsAt                     pgtype.Timestamptz
	Version                    int32
	JobType                    string
	JVolumeM3                  string
	CustomerName               string
	Street                     string
	PostalCode                 string
	Locality                   string
	CountryCode                string
	Latitude                   string
	Longitude                  string
	DriverNames                string
	ResourceNames              string
	ChipperNames               string
	LatestNote                 string
	AvailabilityOverrideReason string
}

func (q *Queries) ListDashboardAppointments(ctx context.Context, arg ListDashboardAppointmentsParams) ([]ListDashboardAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardAppointments, arg.RangeEnd, arg.RangeStart, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardAppointmentsRow{}
	for rows.Next() {
		var i ListDashboardAppointmentsRow
		if err := rows.Scan(
			&i.AID,
			&i.AJobID,
			&i.CustomerID,
			&i.JobNumber,
			&i.LifecycleStatus,
			&i.ConfirmationStatus,
			&i.StartsAt,
			&i.EndsAt,
			&i.Version,
			&i.JobType,
			&i.JVolumeM3,
			&i.CustomerName,
			&i.Street,
			&i.PostalCode,
			&i.Locality,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.DriverNames,
			&i.ResourceNames,
			&i.ChipperNames,
			&i.LatestNote,
			&i.AvailabilityOverrideReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardChipperBookings = `-- name: ListDashboardChipperBookings :many
SELECT r.id::text AS resource_id, r.name AS resource_name,
       ar.reserved_starts_at, ar.reserved_ends_at
FROM resources r
LEFT JOIN appointment_resources ar ON ar.resource_id=r.id AND ar.active
  AND ar.reserved_starts_at < $1::timestamptz
  AND ar.reserved_ends_at > $2::timestamptz
WHERE r.active AND r.resource_type='chipper'
ORDER BY lower(r.name), r.id, ar.reserved_starts_at NULLS LAST
`

type ListDashboardChipperBookingsParams struct {
	CapacityEnd   pgtype.Timestamptz
	CapacityStart pgtype.Timestamptz
}

type ListDashboardChipperBookingsRow struct {
	ResourceID       string
	ResourceName     string
	ReservedStartsAt pgtype.Timestamptz
	ReservedEndsAt   pgtype.Timestamptz
}

func (q *Queries) ListDashboardChipperBookings(ctx context.Context, arg ListDashboardChipperBookingsParams) ([]ListDashboardChipperBookingsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardChipperBookings, arg.CapacityEnd, arg.CapacityStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardChipperBookingsRow{}
	for rows.Next() {
		var i ListDashboardChipperBookingsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.ResourceName,
			&i.ReservedStartsAt,
			&i.ReservedEndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardDriverAvailability = `-- name: ListDashboardDriverAvailability :many
SELECT d.id::text, COALESCE(d.user_id::text, '')::text AS user_id, d.display_name,
       EXISTS (
         SELECT 1 FROM availability_rules r
         WHERE r.driver_id=d.id AND r.iso_weekday=$1::smallint
           AND r.valid_from <= $2::date
           AND (r.valid_until IS NULL OR r.valid_until >= $2::date)
       ) AS has_rule,
       EXISTS (
         SELECT 1 FROM availability_rules r
         WHERE r.driver_id=d.id AND r.iso_weekday=$1::smallint AND r.status='limited'
           AND r.valid_from <= $2::date
           AND (r.valid_until IS NULL OR r.valid_until >= $2::date)
       ) AS has_limited_rule,
       EXISTS (
         SELECT 1 FROM availability_exceptions e
         WHERE e.driver_id=d.id AND e.exception_type='available_override'
           AND ((e.all_day AND e.local_date=$2::date)
             OR (NOT e.all_day AND e.starts_at < $3::timestamptz AND e.ends_at > $4::timestamptz))
       ) AS has_available_override,
       EXISTS (
         SELECT 1 FROM availability_exceptions e
         WHERE e.driver_id=d.id AND e.exception_type<>'available_override'
           AND ((e.all_day AND e.local_date=$2::date)
             OR (NOT e.all_day AND e.starts_at < $3::timestamptz AND e.ends_at > $4::timestamptz))
       ) AS has_unavailable_exception,
       COALESCE((SELECT string_agg(to_char(r.local_start, 'HH24:MI') || '–' || to_char(r.local_end, 'HH24:MI'), ', ' ORDER BY r.local_start)
         FROM availability_rules r
         WHERE r.driver_id=d.id AND r.iso_weekday=$1::smallint
           AND r.valid_from <= $2::date
           AND (r.valid_until IS NULL OR r.valid_until >= $2::date)), '')::text AS availability_windows,
       COALESCE((SELECT string_agg(DISTINCT CASE e.exception_type WHEN 'sick' THEN 'krank' WHEN 'vacation' THEN 'Urlaub' WHEN 'unavailable' THEN 'nicht verfügbar' ELSE 'Sonderverfügbarkeit' END, ', ')
         FROM availability_exceptions e
         WHERE e.driver_id=d.id AND ((e.all_day AND e.local_date=$2::date)
           OR (NOT e.all_day AND e.starts_at < $3::timestamptz AND e.ends_at > $4::timestamptz))), '')::text AS exception_reasons,
       COALESCE((SELECT round(sum(EXTRACT(EPOCH FROM (LEAST(a.ends_at, $3::timestamptz) - GREATEST(a.starts_at, $4::timestamptz))) / 60))::integer
         FROM appointment_drivers ad JOIN appointments a ON a.id=ad.appointment_id
         WHERE ad.driver_id=d.id AND a.lifecycle_status IN ('proposal','fixed')
           AND a.starts_at < $3::timestamptz AND a.ends_at > $4::timestamptz), 0)::integer AS booked_minutes
FROM drivers d
WHERE d.active
ORDER BY lower(d.display_name), d.id
LIMIT 200
`

type ListDashboardDriverAvailabilityParams struct {
	IsoWeekday int16
	LocalDate  pgtype.Date
	DayEnd     pgtype.Timestamptz
	DayStart   pgtype.Timestamptz
}

type ListDashboardDriverAvailabilityRow struct {
	DID                     string
	UserID                  string
	DisplayName             string
	HasRule                 bool
	HasLimitedRule          bool
	HasAvailableOverride    bool
	HasUnavailableException bool
	AvailabilityWindows     string
	ExceptionReasons        string
	BookedMinutes           int32
}

func (q *Queries) ListDashboardDriverAvailability(ctx context.Context, arg ListDashboardDriverAvailabilityParams) ([]ListDashboardDriverAvailabilityRow, error) {
	rows, err := q.db.Query(ctx, listDashboardDriverAvailability,
		arg.IsoWeekday,
		arg.LocalDate,
		arg.DayEnd,
		arg.DayStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardDriverAvailabilityRow{}
	for rows.Next() {
		var i ListDashboardDriverAvailabilityRow
		if err := rows.Scan(
			&i.DID,
			&i.UserID,
			&i.DisplayName,
			&i.HasRule,
			&i.HasLimitedRule,
			&i.HasAvailableOverride,
			&i.HasUnavailableException,
			&i.AvailabilityWindows,
			&i.ExceptionReasons,
			&i.BookedMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardUnplannedJobs = `-- name: ListDashboardUnplannedJobs :many
SELECT j.id::text, j.customer_id::text AS customer_id, j.job_number, j.urgency, j.volume_m3::text, j.received_at,
       j.preferred_end_date,
       concat_ws(' ', NULLIF(c.first_name,''), NULLIF(c.last_name,''), NULLIF(c.company_name,''))::text AS customer_name,
       c.locality
FROM waitlist_entries w
JOIN jobs j ON j.id=w.job_id
JOIN customers c ON c.id=j.customer_id
WHERE w.removed_at IS NULL AND j.archived_at IS NULL AND c.archived_at IS NULL
  AND NOT EXISTS (SELECT 1 FROM appointments a WHERE a.job_id=j.id AND a.lifecycle_status IN ('proposal','fixed'))
ORDER BY w.manual_priority DESC,
         array_position(ARRAY['urgent','high','normal','low'], j.urgency),
         j.preferred_end_date NULLS LAST, w.entered_at, w.id
LIMIT $1
`

type ListDashboardUnplannedJobsRow struct {
	JID              string
	CustomerID       string
	JobNumber        string
	Urgency          string
	JVolumeM3        string
	ReceivedAt       pgtype.Timestamptz
	PreferredEndDate pgtype.Date
	CustomerName     string
	Locality         string
}

func (q *Queries) ListDashboardUnplannedJobs(ctx context.Context, resultLimit int32) ([]ListDashboardUnplannedJobsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardUnplannedJobs, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardUnplannedJobsRow{}
	for rows.Next() {
		var i ListDashboardUnplannedJobsRow
		if err := rows.Scan(
			&i.JID,
			&i.CustomerID,
			&i.JobNumber,
			&i.Urgency,
			&i.JVolumeM3,
			&i.ReceivedAt,
			&i.PreferredEndDate,
			&i.CustomerName,
			&i.Locality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardUrgentJobs = `-- name: ListDashboardUrgentJobs :many
SELECT j.id::text, j.customer_id::text AS customer_id, j.job_number, j.urgency, j.volume_m3::text, j.received_at,
       j.preferred_end_date,
       concat_ws(' ', NULLIF(c.first_name,''), NULLIF(c.last_name,''), NULLIF(c.company_name,''))::text AS customer_name,
       c.locality
FROM waitlist_entries w
JOIN jobs j ON j.id=w.job_id
JOIN customers c ON c.id=j.customer_id
WHERE w.removed_at IS NULL AND j.archived_at IS NULL AND c.archived_at IS NULL
  AND (j.urgency IN ('high','urgent') OR j.received_at <= $1::timestamptz
       OR (j.preferred_end_date IS NOT NULL AND j.preferred_end_date <= $2::date))
ORDER BY array_position(ARRAY['urgent','high','normal','low'], j.urgency),
         j.preferred_end_date NULLS LAST, j.received_at, j.id
LIMIT $3
`

type ListDashboardUrgentJobsParams struct {
	OldBefore       pgtype.Timestamptz
	PreferredBefore pgtype.Date
	ResultLimit     int32
}

type ListDashboardUrgentJobsRow struct {
	JID              string
	CustomerID       string
	JobNumber        string
	Urgency          string
	JVolumeM3        string
	ReceivedAt       pgtype.Timestamptz
	PreferredEndDate pgtype.Date
	CustomerName     string
	Locality         string
}

func (q *Queries) ListDashboardUrgentJobs(ctx context.Context, arg ListDashboardUrgentJobsParams) ([]ListDashboardUrgentJobsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardUrgentJobs, arg.OldBefore, arg.PreferredBefore, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardUrgentJobsRow{}
	for rows.Next() {
		var i ListDashboardUrgentJobsRow
		if err := rows.Scan(
			&i.JID,
			&i.CustomerID,
			&i.JobNumber,
			&i.Urgency,
			&i.JVolumeM3,
			&i.ReceivedAt,
			&i.PreferredEndDate,
			&i.CustomerName,
			&i.Locality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
