// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
DELETE FROM auth_rate_limits WHERE key_hash = $1
`

func (q *Queries) ClearLoginFailures(ctx context.Context, keyHash []byte) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, keyHash)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE active AND role = 'admin'
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE revoked_at IS NOT NULL OR idle_expires_at <= now() OR absolute_expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findRateLimit = `-- name: FindRateLimit :one
SELECT window_started_at, failure_count FROM auth_rate_limits WHERE key_hash = $1
`

type FindRateLimitRow struct {
	WindowStartedAt pgtype.Timestamptz
	FailureCount    int32
}

func (q *Queries) FindRateLimit(ctx context.Context, keyHash []byte) (FindRateLimitRow, error) {
	row := q.db.QueryRow(ctx, findRateLimit, keyHash)
	var i FindRateLimitRow
	err := row.Scan(&i.WindowStartedAt, &i.FailureCount)
	return i, err
}

const findSession = `-- name: FindSession :one
SELECT s.id::text, s.user_id::text, s.csrf_token_hash, s.idle_expires_at,
       s.absolute_expires_at, s.revoked_at, u.username::text, u.display_name,
       u.role, u.must_change_password, u.active, COALESCE(d.id::text, '')::text AS driver_id, u.version
FROM sessions s
JOIN users u ON u.id = s.user_id
LEFT JOIN drivers d ON d.user_id = u.id
WHERE s.token_hash = $1
`

type FindSessionRow struct {
	SID                string
	SUserID            string
	CsrfTokenHash      []byte
	IdleExpiresAt      pgtype.Timestamptz
	AbsoluteExpiresAt  pgtype.Timestamptz
	RevokedAt          pgtype.Timestamptz
	UUsername          string
	DisplayName        string
	Role               string
	MustChangePassword bool
	Active             bool
	DriverID           string
	Version            int32
}

func (q *Queries) FindSession(ctx context.Context, tokenHash []byte) (FindSessionRow, error) {
	row := q.db.QueryRow(ctx, findSession, tokenHash)
	var i FindSessionRow
	err := row.Scan(
		&i.SID,
		&i.SUserID,
		&i.CsrfTokenHash,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.RevokedAt,
		&i.UUsername,
		&i.DisplayName,
		&i.Role,
		&i.MustChangePassword,
		&i.Active,
		&i.DriverID,
		&i.Version,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT u.id::text, u.username::text, u.display_name, COALESCE(u.email::text, '')::text AS email,
       u.role, u.password_hash, u.must_change_password, u.active, u.version,
       COALESCE(d.id::text, '')::text AS driver_id
FROM users u
LEFT JOIN drivers d ON d.user_id = u.id
WHERE u.id = $1::uuid
`

type FindUserByIDRow struct {
	UID                string
	UUsername          string
	DisplayName        string
	Email              string
	Role               string
	PasswordHash       string
	MustChangePassword bool
	Active             bool
	Version            int32
	DriverID           string
}

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.UID,
		&i.UUsername,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.Active,
		&i.Version,
		&i.DriverID,
	)
	return i, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT u.id::text AS id, u.username::text AS username, u.display_name,
       COALESCE(u.email::text, '')::text AS email, u.role, u.password_hash,
       u.must_change_password, u.active, u.version,
       COALESCE(d.id::text, '')::text AS driver_id
FROM users u
LEFT JOIN drivers d ON d.user_id = u.id
WHERE u.username = $1
`

type FindUserByUsernameRow struct {
	ID                 string
	Username           string
	DisplayName        string
	Email              string
	Role               string
	PasswordHash       string
	MustChangePassword bool
	Active             bool
	Version            int32
	DriverID           string
}

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (FindUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i FindUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.MustChangePassword,
		&i.Active,
		&i.Version,
		&i.DriverID,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_type, actor_user_id, action, object_type, object_id, request_id, metadata)
VALUES ($1, NULLIF($2::text, '')::uuid, $3, $4, NULLIF($5::text, ''), NULLIF($6::text, ''), $7)
`

type InsertAuditEventParams struct {
	ActorType   string
	ActorUserID string
	Action      string
	ObjectType  string
	ObjectID    string
	RequestID   string
	Metadata    []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorType,
		arg.ActorUserID,
		arg.Action,
		arg.ObjectType,
		arg.ObjectID,
		arg.RequestID,
		arg.Metadata,
	)
	return err
}

const insertDriver = `-- name: InsertDriver :one
INSERT INTO drivers (user_id, display_name, email)
VALUES (NULLIF($1::text, '')::uuid, $2, NULLIF($3::text, '')::citext)
RETURNING id::text
`

type InsertDriverParams struct {
	UserID      string
	DisplayName string
	Email       string
}

func (q *Queries) InsertDriver(ctx context.Context, arg InsertDriverParams) (string, error) {
	row := q.db.QueryRow(ctx, insertDriver, arg.UserID, arg.DisplayName, arg.Email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (user_id, token_hash, csrf_token_hash, idle_expires_at, absolute_expires_at)
VALUES ($1::uuid, $2, $3, $4, $5)
RETURNING id::text
`

type InsertSessionParams struct {
	UserID            pgtype.UUID
	TokenHash         []byte
	CsrfTokenHash     []byte
	IdleExpiresAt     pgtype.Timestamptz
	AbsoluteExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfTokenHash,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, display_name, email, role, password_hash, must_change_password)
VALUES ($1, $2, NULLIF($3::text, '')::citext, $4, $5, $6)
RETURNING id::text
`

type InsertUserParams struct {
	Username           string
	DisplayName        string
	Email              string
	Role               string
	PasswordHash       string
	MustChangePassword bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (string, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
		arg.MustChangePassword,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id::text, u.username::text, u.display_name, COALESCE(u.email::text, '')::text AS email,
       u.role, u.must_change_password, u.active, u.last_login_at, u.version,
       COALESCE(d.id::text, '')::text AS driver_id
FROM users u
LEFT JOIN drivers d ON d.user_id = u.id
ORDER BY lower(u.username::text)
`

type ListUsersRow struct {
	UID                string
	UUsername          string
	DisplayName        string
	Email              string
	Role               string
	MustChangePassword bool
	Active             bool
	LastLoginAt        pgtype.Timestamptz
	Version            int32
	DriverID           string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.UID,
			&i.UUsername,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.MustChangePassword,
			&i.Active,
			&i.LastLoginAt,
			&i.Version,
			&i.DriverID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLogin = `-- name: MarkLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now() WHERE id = $1::uuid
`

func (q *Queries) MarkLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markLogin, id)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
INSERT INTO auth_rate_limits (key_hash, window_started_at, failure_count)
VALUES ($1, now(), 1)
ON CONFLICT (key_hash) DO UPDATE
SET failure_count = CASE WHEN auth_rate_limits.window_started_at < now() - interval '1 minute' THEN 1 ELSE auth_rate_limits.failure_count + 1 END,
    window_started_at = CASE WHEN auth_rate_limits.window_started_at < now() - interval '1 minute' THEN now() ELSE auth_rate_limits.window_started_at END,
    updated_at = now()
`

func (q *Queries) RecordLoginFailure(ctx context.Context, keyHash []byte) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, keyHash)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = COALESCE(revoked_at, now()) WHERE token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = now(), idle_expires_at = LEAST($1, absolute_expires_at)
WHERE id = $2::uuid AND revoked_at IS NULL
`

type TouchSessionParams struct {
	IdleExpiresAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.IdleExpiresAt, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :execrows
UPDATE users
SET password_hash = $1, must_change_password = $2,
    version = version + 1, updated_at = now()
WHERE id = $3::uuid AND version = $4
`

type UpdatePasswordParams struct {
	PasswordHash       string
	MustChangePassword bool
	ID                 pgtype.UUID
	ExpectedVersion    int32
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePassword,
		arg.PasswordHash,
		arg.MustChangePassword,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserAccess = `-- name: UpdateUserAccess :execrows
UPDATE users
SET role = $1, active = $2, version = version + 1, updated_at = now()
WHERE id = $3::uuid AND version = $4
`

type UpdateUserAccessParams struct {
	Role            string
	Active          bool
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateUserAccess(ctx context.Context, arg UpdateUserAccessParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserAccess,
		arg.Role,
		arg.Active,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserDetails = `-- name: UpdateUserDetails :execrows
UPDATE users
SET username = $1, display_name = $2,
    email = NULLIF($3::text, '')::citext,
    version = version + 1, updated_at = now()
WHERE id = $4::uuid AND version = $5
`

type UpdateUserDetailsParams struct {
	Username        string
	DisplayName     string
	Email           string
	ID              pgtype.UUID
	ExpectedVersion int32
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserDetails,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
