CREATE ROLE hackplan_migrate LOGIN PASSWORD 'development-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE hackplan_app LOGIN PASSWORD 'development-only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE hackplan OWNER hackplan_migrate;

\connect hackplan

GRANT CONNECT ON DATABASE hackplan TO hackplan_app;
GRANT USAGE ON SCHEMA public TO hackplan_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hackplan_migrate IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hackplan_app;
ALTER DEFAULT PRIVILEGES FOR ROLE hackplan_migrate IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hackplan_app;
